### PR TITLE
Changed read-only flag of software proposal to soft one

### PR DESCRIPTION
**Pull request by mchf**
https://trello.com/c/sEVjWKcJ/780-3-casp-read-only-software-selection

### CODE REVIEW

**Comment by imobachgs** [comment]
I would update the dependency on `yast2-installation` to ` 3.1.217.9` (from  https://github.com/yast/yast-installation/pull/483/files). Otherwise, it looks good.

**Review by lslezak — COMMENTED** [review]
Um, according to [this PBI](https://trello.com/c/SP8zbapS/815-2-casp-adjust-workflow-control-file-to-new-requirements) the CASP should have only a single "main" dialog without the installation proposal. That means this change will be removed later anyway.

So does it still make sense to merge this?

**Comment by mchf** [comment]
I'd keep it for consistency, when the implementation is in yast2-installation lets have it even here e.g. if someone needs to track history in the future (?)

**Review by lslezak — APPROVED** [review]
OK, let's keep it for the consistency with the other packages...

**Review by imobachgs — APPROVED** [review]

**Comment by lslezak** [comment]
I'm fine with merging (the Travis needs new rebuilt dependent packages which might take ages for Ubuntu builds...).

**Comment by mchf** [comment]
Thanks for reviews

**Pull request merged**
