### PR TITLE
[WIP] Added all in one overview and removed unnecessary options (Fate#322328)

### PR DESCRIPTION
**Pull request by teclator**
Added casp overview and removed some unnecessary options.

- https://github.com/yast/yast-installation/pull/487
- https://fate.suse.com/322328

### CODE REVIEW

**Comment by mvidner** [comment]
Thanks!

But we cannot merge this until https://github.com/yast/yast-installation/pull/487 and its dependencies are merged, otherwise the ISO will break.

**Comment by teclator** [comment]
@mvidner I have added [WIP] to the title to make it more clear, my idea was not to merge it until yast/yast-installation#487 was merged, so maybe should be reasonable to create also the all-in-one-overview branch in this repository althought in this case it should be merged after instead of before the commented PR.

**Comment by jreidinger** [comment]
thanks, please merge it and will continue working on it

**Comment by teclator** [comment]
@jreidinger thnx for taking care ;)

**Pull request merged**
