### PR TITLE
CaaSP 4 pulls images from SUSE Registry, so we don't need

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
container-feeder anymore

Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
@teclator : Hi! Could you take a look at these one? Our devel isos are broken because of this, since we are not installing container-feeder but yast tries to start the service. Thanks.

**Comment by teclator** [comment]
For me it is fine, but It needs a bug report / or a feature request and the the changelog entry as well.

**Comment by jordimassaguerpla** [comment]
@teclator : I just opened a bug and rebased this commit so it contains the reference in the changelog and increased the version to reflect that.
Could you review again?

**Comment by teclator** [comment]
@jordimassaguerpla it still has some pending conflict, you should rebase it with master.

**Review by teclator — CHANGES_REQUESTED** [review]
Rebase with master

**Comment by jordimassaguerpla** [comment]
Rebased with master.

**Review by teclator — APPROVED** [review]

**Comment by teclator** [comment]
LGTM

**Comment by teclator** [comment]
Created request to SUSE:SLE-15:Update:Products:CASP40 (https://build.suse.de/request/show/174773)

**Pull request merged**
